apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: default
spec:
  clusterIP: None
  ports:
  - port: 2379
    name: client
    targetPort: 2379
  - port: 2380
    name: peer
    targetPort: 2380
  selector:
    app: etcd
